# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bdcf74579e04e94c57f003e3b93add68618c9cea23827aef214ceda0649c30d651a54201b761441cffaca3cff14647fc7ab6131a552cc7b9c4ddd94ed5e8866

test:
  secret_key_base: d3647ebea18ff637b228bd07ba92900f277813de4db71979b29da3e0c2f57b6483c9a300306aca9e1948e0e54b0e091e549a3ad831f4eba909d7ad8ebc7c6bef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
